name: Update Changelog

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'composer.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Generate Changelog
        uses: TriPSs/conventional-changelog-action@v6
        id: changelog
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          git-push: 'false'
          output-file: 'CHANGELOG.md'
          skip-version-file: 'true'
          
      - name: Create Pull Request
        if: steps.changelog.outputs.skipped == 'false'
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          commit-message: 'chore(release): v${{ steps.changelog.outputs.version }}'
          branch: 'release/v${{ steps.changelog.outputs.version }}'
          title: 'chore(release): v${{ steps.changelog.outputs.version }}'
          body: |
            ## Automated Release PR
            This PR updates the **CHANGELOG.md** for version ${{ steps.changelog.outputs.version }}.
            
            ${{ steps.changelog.outputs.clean_changelog }}
          base: main

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}